package {
	import de.polygonal.core.ObjectPool;

	import com.nbilyk.display.BetterCanvas;
	import com.nbilyk.display.BetterFormItem;
	import com.nbilyk.display.BetterText;
	import com.nbilyk.display.CSSComponent;
	import com.nbilyk.display.CSSText;
	import com.nbilyk.display.GradientCanvas;
	import com.nbilyk.display.IPreloader;
	import com.nbilyk.display.MessageNotifier;
	import com.nbilyk.display.QueuedImage;
	import com.nbilyk.effects.BitmapEffect;
	import com.nbilyk.effects.BitmapFadeEffect;
	import com.nbilyk.effects.BitmapWipeEffect;
	import com.nbilyk.effects.bitmaptransitions.BitmapFadeTransition;
	import com.nbilyk.effects.bitmaptransitions.BitmapTransition;
	import com.nbilyk.effects.bitmaptransitions.BitmapWipeTransition;
	import com.nbilyk.effects.effectclasses.BitmapEffectInstance;
	import com.nbilyk.effects.effectclasses.BitmapFadeEffectInstance;
	import com.nbilyk.effects.effectclasses.BitmapWipeEffectInstance;
	import com.nbilyk.events.LoaderCreationEvent;
	import com.nbilyk.events.QueuedUrlLoaderEvent;
	import com.nbilyk.file.FormContent;
	import com.nbilyk.file.MultipartUrlLoader;
	import com.nbilyk.flexvideoplayer.FlexVideoPlayer;
	import com.nbilyk.flexvideoplayer.VideoControlBar;
	import com.nbilyk.formatters.FileSizeFormatter;
	import com.nbilyk.history.HistoryTracker;
	import com.nbilyk.history.IPrettyHistoryManagerClient;
	import com.nbilyk.history.PrettyHistoryManager;
	import com.nbilyk.logging.ArrayTarget;
	import com.nbilyk.logging.DebugPanel;
	import com.nbilyk.naddress.NAddress;
	import com.nbilyk.naddress.NAddressPrettyHistory;
	import com.nbilyk.popup.NPopUp;
	import com.nbilyk.popup.PopUpDescriptor;
	import com.nbilyk.preloader.NFlexPreloader;
	import com.nbilyk.preloader.NPreloader;
	import com.nbilyk.preloader.NPreloaderController;
	import com.nbilyk.sharedobject.AbstractPersistantData;
	import com.nbilyk.utils.ArrayUtils;
	import com.nbilyk.utils.ByteArrayUtils;
	import com.nbilyk.utils.ComponentUtil;
	import com.nbilyk.utils.CoordMath;
	import com.nbilyk.utils.DateUtils;
	import com.nbilyk.utils.DeferredFunctionCall;
	import com.nbilyk.utils.DisplayObjectUtils;
	import com.nbilyk.utils.EventQueue;
	import com.nbilyk.utils.FunctionFactory;
	import com.nbilyk.utils.FunctionUtils;
	import com.nbilyk.utils.KeyboardTabFocusScroller;
	import com.nbilyk.utils.KineticScrollManager;
	import com.nbilyk.utils.ListRecycler;
	import com.nbilyk.utils.LoaderQueue;
	import com.nbilyk.utils.LoaderQueueManager;
	import com.nbilyk.utils.MathUtils;
	import com.nbilyk.utils.ObjectUtils;
	import com.nbilyk.utils.ParsingUtil;
	import com.nbilyk.utils.QueuedEvent;
	import com.nbilyk.utils.StringUtils;
	import com.nbilyk.utils.StyleUtil;
	import com.nbilyk.utils.UniqueStringFilter;
	import com.nbilyk.utils.XMLUtils;
	import com.nbilyk.validators.ConfirmationValidator;
	import com.nbilyk.validators.URLValidator;

	public class NBFlexLibClasses {
		ObjectPool;
		
		HistoryTracker;
		ComponentUtil;
		LoaderCreationEvent;
		BitmapTransition;
		BetterText;
		CSSText;
		BetterFormItem;
		ArrayTarget;
		StringUtils;
		ConfirmationValidator;
		MathUtils;
		ObjectUtils;
		KineticScrollManager;
		LoaderQueue;
		ParsingUtil;
		AbstractPersistantData;
		XMLUtils;
		ArrayUtils;
		StyleUtil;
		CoordMath;
		URLValidator;
		GradientCanvas;
		DisplayObjectUtils;
		BitmapFadeTransition;
		FileSizeFormatter;
		BitmapWipeEffectInstance;
		QueuedUrlLoaderEvent;
		EventQueue;
		LoaderQueueManager;
		BitmapFadeEffectInstance;
		QueuedImage;
		CSSComponent;
		UniqueStringFilter;
		ByteArrayUtils;
		FlexVideoPlayer;
		DeferredFunctionCall;
		FunctionUtils;
		VideoControlBar;
		BitmapWipeEffect;
		MessageNotifier;
		BitmapEffectInstance;
		DateUtils;
		IPreloader;
		BitmapEffect;
		BitmapWipeTransition;
		IPrettyHistoryManagerClient;
		BitmapFadeEffect;
		QueuedEvent;
		PrettyHistoryManager;
		ListRecycler;
		DebugPanel;
		KeyboardTabFocusScroller;
		NAddress;
		NAddressPrettyHistory;
		BetterCanvas;
		FunctionFactory;
		NPopUp;
		PopUpDescriptor;
		NFlexPreloader;
		NPreloaderController;
		NPreloader;
		FormContent;
		MultipartUrlLoader;
	}
}